//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NitroType3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UsrCnf_AutoStart {
            get {
                return ((bool)(this["UsrCnf_AutoStart"]));
            }
            set {
                this["UsrCnf_AutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsrCnf_AutoGame {
            get {
                return ((bool)(this["UsrCnf_AutoGame"]));
            }
            set {
                this["UsrCnf_AutoGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsrCnf_UseNitros {
            get {
                return ((bool)(this["UsrCnf_UseNitros"]));
            }
            set {
                this["UsrCnf_UseNitros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int UsrCnf_Accuracy {
            get {
                return ((int)(this["UsrCnf_Accuracy"]));
            }
            set {
                this["UsrCnf_Accuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UsrCnf_AccuracyV {
            get {
                return ((int)(this["UsrCnf_AccuracyV"]));
            }
            set {
                this["UsrCnf_AccuracyV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("260")]
        public int UsrCnf_TypingRate_Real {
            get {
                return ((int)(this["UsrCnf_TypingRate_Real"]));
            }
            set {
                this["UsrCnf_TypingRate_Real"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UsrCnf_TypingRateV {
            get {
                return ((int)(this["UsrCnf_TypingRateV"]));
            }
            set {
                this["UsrCnf_TypingRateV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UsrCnf_OpenAmount {
            get {
                return ((int)(this["UsrCnf_OpenAmount"]));
            }
            set {
                this["UsrCnf_OpenAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int UsrCnf_TypingRate_Visual {
            get {
                return ((int)(this["UsrCnf_TypingRate_Visual"]));
            }
            set {
                this["UsrCnf_TypingRate_Visual"] = value;
            }
        }
    }
}
